// d = difficulty, a = index of correct option, exp = scientific explanation.
export const BANK = [
  {
    id: 1,
    d: 'Easy',
    q: 'Biomedical engineering combines engineering principles with:',
    o: ['Only physics', 'Biology and medicine', 'Only chemistry', 'Economics'],
    a: 1,
    exp: 'Biomedical engineering (BME) bridges classical engineering principles (electrical, mechanical, chemical, and computational) with biology and medical sciences to develop healthcare diagnostics, medical devices, and therapeutic interventions.'
  },
  {
    id: 2,
    d: 'Easy',
    q: 'An ECG records the electrical activity of the:',
    o: ['Brain', 'Muscles', 'Heart', 'Lungs'],
    a: 2,
    exp: 'An Electrocardiogram (ECG/EKG) captures the bioelectric potentials generated by the rhythmic depolarization and repolarization of myocardial muscle fibers during cardiac cycles.'
  },
  {
    id: 3,
    d: 'Easy',
    q: 'EEG measures signals from the:',
    o: ['Brain', 'Heart', 'Eyes', 'Nerves in the leg'],
    a: 0,
    exp: 'Electroencephalography (EEG) non-invasively detects and records the electrical fluctuations originating from postsynaptic pyramidal neurons within the cerebral cortex of the brain.'
  },
  {
    id: 4,
    d: 'Easy',
    q: 'EMG measures the electrical activity of:',
    o: ['Heart', 'Brain', 'Skeletal muscles', 'Stomach'],
    a: 2,
    exp: 'Electromyography (EMG) evaluates motor unit action potentials (MUAPs) produced by skeletal muscle fibers during neuromuscular stimulation and physical contraction.'
  },
  {
    id: 5,
    d: 'Easy',
    q: 'The normal resting heart rate of an adult is about:',
    o: ['20-40 bpm', '60-100 bpm', '120-160 bpm', '180-220 bpm'],
    a: 1,
    exp: 'A healthy adult resting heart rate typically ranges from 60 to 100 beats per minute (bpm). A rate lower than 60 bpm is classified as bradycardia, while above 100 bpm is tachycardia.'
  },
  {
    id: 6,
    d: 'Easy',
    q: 'A sphygmomanometer is used to measure:',
    o: ['Body temperature', 'Blood glucose', 'Blood pressure', 'Lung capacity'],
    a: 2,
    exp: 'A sphygmomanometer utilizes an occluding inflatable cuff and a manometer (mercury, aneroid, or digital) to measure arterial systolic and diastolic blood pressure.'
  },
  {
    id: 7,
    d: 'Easy',
    q: 'A pulse oximeter measures:',
    o: ['Blood oxygen saturation (SpO₂)', 'Body fat', 'Blood sugar', 'Brain activity'],
    a: 0,
    exp: 'A pulse oximeter employs photoplethysmography (PPG) to measure peripheral capillary oxygen saturation (SpO₂)—the ratio of oxygenated hemoglobin to total hemoglobin in arterial blood.'
  },
  {
    id: 8,
    d: 'Easy',
    q: 'X-ray imaging uses:',
    o: ['Sound waves', 'Ionizing radiation', 'Magnetic fields only', 'Visible light'],
    a: 1,
    exp: 'X-rays consist of high-energy electromagnetic ionizing radiation capable of penetrating anatomical tissues, producing planar transmission images based on tissue electron density and atomic number.'
  },
  {
    id: 9,
    d: 'Easy',
    q: 'Ultrasound imaging uses:',
    o: ['High-frequency sound waves', 'X-rays', 'Gamma rays', 'Radio waves only'],
    a: 0,
    exp: 'Diagnostic ultrasound uses non-ionizing mechanical longitudinal waves (typically 2 MHz to 18 MHz) that reflect off internal acoustic impedance boundaries to produce real-time cross-sectional images.'
  },
  {
    id: 10,
    d: 'Easy',
    q: 'MRI uses:',
    o: ['X-rays', 'Ultrasound', 'Strong magnetic fields and radio waves', 'Infrared light'],
    a: 2,
    exp: 'Magnetic Resonance Imaging (MRI) aligns the magnetic moments of hydrogen nuclei (protons) in human tissue using strong static magnetic fields (B₀) and excites them with radiofrequency (RF) electromagnetic pulses.'
  },
  {
    id: 11,
    d: 'Easy',
    q: 'A pacemaker is implanted to:',
    o: ['Measure blood pressure', 'Regulate heartbeat using electrical pulses', 'Pump blood fully', 'Filter blood'],
    a: 1,
    exp: 'An implantable cardiac pacemaker monitors heart rhythm and delivers small electrical impulses to the myocardium to maintain adequate heart rate when intrinsic conductive pathways fail.'
  },
  {
    id: 12,
    d: 'Easy',
    q: 'A defibrillator is used to:',
    o: ['Deliver an electric shock to restore a normal heart rhythm', 'Measure heart rate', 'Dilate blood vessels', 'Record EEG'],
    a: 0,
    exp: 'A defibrillator discharges a controlled therapeutic dose of electrical energy through the myocardium to depolarize a critical mass of cardiac muscle, terminating life-threatening ventricular fibrillation or tachycardia.'
  },
  {
    id: 13,
    d: 'Easy',
    q: '"Biocompatible" means a material:',
    o: ['Is cheap', 'Is magnetic', 'Is transparent', 'Does not cause harmful reactions in the body'],
    a: 3,
    exp: 'Biocompatibility denotes the capability of an engineered biomaterial or implant to interact safely within a physiological environment without triggering severe toxic, inflammatory, allergic, or thrombogenic reactions.'
  },
  {
    id: 14,
    d: 'Easy',
    q: 'A biosensor detects:',
    o: ['Only temperature', 'A biological substance and converts it into a measurable signal', 'Only light', 'Only sound'],
    a: 1,
    exp: 'A biosensor integrates a biological biorecognition element (such as an enzyme, antibody, or nucleic acid) with a physicochemical transducer to convert biochemical analyte interactions into quantifiable electrical signals.'
  },
  {
    id: 15,
    d: 'Easy',
    q: 'The unit of frequency is:',
    o: ['Volt', 'Ohm', 'Hertz', 'Watt'],
    a: 2,
    exp: 'The International System of Units (SI) unit of frequency is the Hertz (Hz), defined as one cycle or complete oscillation per second (1 Hz = 1 s⁻¹).'
  },
  {
    id: 16,
    d: 'Easy',
    q: 'An ECG electrode placed on the skin is used to:',
    o: ['Inject medicine', 'Heat the skin', 'Pick up small electrical signals from the body', 'Measure pressure'],
    a: 2,
    exp: 'ECG surface electrodes (typically Ag/AgCl) act as transducers that convert ionic currents generated by depolarizing body cells into electronic current that can be processed by differential bio-amplifiers.'
  },

  {
    id: 17,
    d: 'Medium',
    q: 'The ECG wave that represents ventricular depolarization is:',
    o: ['P wave', 'QRS complex', 'T wave', 'U wave'],
    a: 1,
    exp: 'The QRS complex corresponds to rapid ventricular depolarization that immediately precedes ventricular myocardial contraction. In comparison, the P wave reflects atrial depolarization and the T wave represents ventricular repolarization.'
  },
  {
    id: 18,
    d: 'Medium',
    q: 'Conductive gel is applied under ECG electrodes to:',
    o: ['Cool the skin', 'Glue the wire', 'Reduce skin-electrode impedance', 'Increase signal frequency'],
    a: 2,
    exp: 'The outer stratum corneum layer of human epidermis presents high capacitive and resistive impedance. Electrolytic conductive gel hydrates the epidermal interface, lowering skin-electrode contact impedance and minimizing motion artifacts.'
  },
  {
    id: 19,
    d: 'Medium',
    q: 'Biopotential amplifiers use instrumentation amplifiers mainly because they have:',
    o: ['Low input impedance', 'High CMRR and high input impedance', 'Zero gain', 'High power consumption'],
    a: 1,
    exp: 'Instrumentation amplifiers feature ultra-high differential input impedance (gigohms, preventing electrode signal attenuation) and a high Common-Mode Rejection Ratio (CMRR > 80–120 dB), which rejects 50/60 Hz powerline interference.'
  },
  {
    id: 20,
    d: 'Medium',
    q: 'Normal SpO₂ in a healthy person is:',
    o: ['50-60%', '70-80%', '95-100%', 'Above 120%'],
    a: 2,
    exp: 'Normal physiological arterial oxygen saturation (SpO₂) in a healthy person breathing ambient air at sea level is 95% to 100%. Clinical hypoxemia is typically flagged when SpO₂ drops below 90–92%.'
  },
  {
    id: 21,
    d: 'Medium',
    q: 'Pulse oximeters work using which two light wavelengths?',
    o: ['Blue and green', 'UV and X-ray', 'Red and infrared', 'Green and yellow'],
    a: 2,
    exp: 'Pulse oximeters rely on optical absorption differentials between oxygenated hemoglobin (HbO₂, absorbing primarily infrared light at ~940 nm) and deoxygenated hemoglobin (Hb, absorbing primarily red light at ~660 nm).'
  },
  {
    id: 22,
    d: 'Medium',
    q: 'According to the Nyquist theorem, the sampling rate must be at least:',
    o: ['Equal to the signal frequency', 'Half the highest frequency', 'Twice the highest frequency', 'Ten times the lowest frequency'],
    a: 2,
    exp: 'The Nyquist-Shannon sampling theorem dictates that to perfectly sample and reconstruct an analog bandlimited signal without spectral aliasing distortion, the sampling frequency fs must be at least twice the maximum signal frequency (fs ≥ 2·f_max).'
  },
  {
    id: 23,
    d: 'Medium',
    q: '50/60 Hz noise in biosignals is caused by powerline interference and is removed using a:',
    o: ['Notch filter', 'High-pass filter at 100 Hz', 'Rectifier', 'Oscillator'],
    a: 0,
    exp: 'A notch filter (band-stop or band-reject filter) provides deep, narrowband attenuation targeted precisely at 50 Hz or 60 Hz mains powerline frequency without distorting adjacent biosignal frequency components.'
  },
  {
    id: 24,
    d: 'Medium',
    q: 'Which imaging method gives excellent soft-tissue detail without ionizing radiation?',
    o: ['X-ray', 'CT scan', 'MRI', 'PET scan'],
    a: 2,
    exp: 'Magnetic Resonance Imaging (MRI) offers peerless soft-tissue contrast resolution (brain grey/white matter, tendons, ligaments, and organs) purely utilizing magnetic fields and radiofrequency pulses without ionizing radiation exposure.'
  },
  {
    id: 25,
    d: 'Medium',
    q: 'The ultrasound transducer typically uses which material?',
    o: ['Piezoelectric crystal', 'Copper wire only', 'Silicon carbide only', 'Rubber'],
    a: 0,
    exp: 'Medical ultrasound transducers utilize piezoelectric materials (most commonly synthetic Lead Zirconate Titanate, PZT) that exhibit reversible electromechanical coupling—converting voltage pulses into sound waves and vice versa.'
  },
  {
    id: 26,
    d: 'Medium',
    q: 'EEG alpha waves have a frequency range of about:',
    o: ['0.5-4 Hz', '8-13 Hz', '30-50 Hz', '100-200 Hz'],
    a: 1,
    exp: 'Alpha brainwaves occupy the 8 to 13 Hz rhythmic band, most prominent over the posterior and occipital lobes when a subject is conscious, mentally relaxed, and resting with closed eyes.'
  },
  {
    id: 27,
    d: 'Medium',
    q: 'A strain gauge measures force by detecting a change in:',
    o: ['Color', 'Temperature only', 'Sound', 'Electrical resistance'],
    a: 3,
    exp: 'A bonded foil strain gauge operates on the piezoresistive principle: applied physical strain alters the conductor’s geometric length and cross-sectional area, causing a measurable proportional variation in electrical resistance.'
  },
  {
    id: 28,
    d: 'Medium',
    q: 'The diagnostic bandwidth of a standard ECG is approximately:',
    o: ['0.05-100 Hz', '1-10 kHz', '1-5 MHz', '500-1000 Hz'],
    a: 0,
    exp: 'Clinical standards set by the American Heart Association (AHA) and IEC require standard diagnostic 12-lead ECG bandwidth to be 0.05 Hz to 100 Hz (or 150 Hz for pediatrics) to preserve baseline ST segment shift and sharp QRS morphological features.'
  },

  {
    id: 29,
    d: 'Tough',
    q: 'An amplifier has differential gain 1000 and common-mode gain 0.1. Its CMRR in dB is:',
    o: ['40 dB', '60 dB', '80 dB', '100 dB'],
    a: 2,
    exp: 'Common-Mode Rejection Ratio (CMRR) is the ratio of differential gain (Ad) to common-mode gain (Acm): CMRR = 1000 / 0.1 = 10,000. Expressed in decibels: CMRR(dB) = 20 × log₁₀(10,000) = 20 × 4 = 80 dB.'
  },
  {
    id: 30,
    d: 'Tough',
    q: 'An EMG signal has useful content up to 500 Hz. The minimum sampling rate is:',
    o: ['250 Hz', '500 Hz', '750 Hz', '1000 Hz'],
    a: 3,
    exp: 'By the Nyquist theorem (fs ≥ 2·f_max), with the maximum frequency component at 500 Hz, the minimum non-aliased sampling frequency is 2 × 500 Hz = 1000 Hz (1000 samples per second).'
  },
  {
    id: 31,
    d: 'Tough',
    q: 'For devices with direct cardiac contact (e.g., catheters), the commonly accepted safe leakage current limit is about:',
    o: ['10 µA', '10 mA', '100 mA', '1 A'],
    a: 0,
    exp: 'Under medical electrical safety standards (IEC 60601-1 Type CF cardiac floating applied parts), maximum allowable patient leakage current under normal conditions is 10 µA (microamperes) to prevent fatal microshock fibrillation.'
  },
  {
    id: 32,
    d: 'Tough',
    q: 'Isolation amplifiers in patient monitors are used mainly to:',
    o: ['Increase gain', 'Reduce cost', 'Protect the patient from electric shock and break ground loops', 'Increase heart rate'],
    a: 2,
    exp: 'Galvanic isolation (via optocouplers, RF transformers, or capacitive barriers) breaks ground loops and protects the patient against lethal high-voltage electrical mains shocks and equipment fault currents.'
  },
  {
    id: 33,
    d: 'Tough',
    q: 'The Right Leg Drive (RLD) circuit in an ECG:',
    o: ['Pumps blood', 'Feeds an inverted common-mode signal back to the patient to reduce interference', 'Amplifies the QRS only', 'Stores data'],
    a: 1,
    exp: 'The Right Leg Drive (RLD) circuit samples common-mode noise voltage from patient limb leads, inverts it through an auxiliary amplifier, and drives it back to the body through the right leg, actively suppressing 50/60 Hz displacement noise currents.'
  },
  {
    id: 34,
    d: 'Tough',
    q: 'In CT imaging, the Hounsfield Unit (HU) value of water is:',
    o: ['-1000', '-100', '0', '+1000'],
    a: 2,
    exp: 'The Hounsfield Unit (HU) CT attenuation scale is mathematically defined with pure water calibrated at 0 HU, air at -1000 HU, and dense cortical bone exceeding +1000 HU.'
  },
  {
    id: 35,
    d: 'Tough',
    q: 'In MRI, the Larmor (resonance) frequency of protons is directly proportional to:',
    o: ['Patient weight', 'Strength of the main magnetic field (B₀)', 'Room temperature', 'Scan duration'],
    a: 1,
    exp: 'The Larmor equation ω₀ = γ · B₀ (or f₀ = (γ / 2π) · B₀) dictates that nuclear precession frequency is directly proportional to the static magnetic field strength B₀ (e.g., ~63.86 MHz at 1.5 Tesla and ~127.7 MHz at 3.0 Tesla for hydrogen nuclei).'
  }
];
